service: aws

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  timeout: 5

functions:
  redirect:
    handler: handler.redirect
    description: Redirect to blog
    timeout: 6
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: cloudspider.io
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true